### ISSUE TITLE
建议添加旁观者模式

### ISSUE THREAD

**Issue by Zi-Gao** [EarthMessenger/ddz_py#1]

**Comment by robinyqc** [comment]
已经有了旁观者模式。游戏开始时，非游玩玩家即为旁观者模式。

不过建议添加命令 /mode spectator，在游戏开始时，不指定 mode 为 spectator 的人加入。

**Comment by EarthMessenger** [comment]
https://github.com/EarthMessenger/ddz_py/commit/c31ae28c706e406fb8d775c5bf72cd7fe02f872c

done
